
# =======================
# == Configuration for fe-sample pod, change host parameters accordingly
# == before doing `kubectl apply -f`
# =======================
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-sample-config
data:
  config.json: |
    {
      "host": "http://besample.australiaeast.cloudapp.azure.com:8888"
    }

---

# ======================
# == Configuration for be-sample pod, change db parameters accordingly
# == before doing `kubectl apply -f`
# =======================
apiVersion: v1
kind: ConfigMap
metadata:
  name: be-sample-config
data:
  config.json: |
    {
      "dbHost": "mariadb.australiaeast.cloudapp.azure.com",
      "dbUsername": "root",
      "dbPassword": "root",
      "dbPort": 3306
    }

---

# =================
# ==  MariaDb service, allow mariadb to be accessible publicly and also by be-sample
# ==    use ClusterIp instead of LoadBalancer if it needs to be only accessible within
# ==    cluster
# =================
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: mariadb
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
    - port: 3306
      protocol: TCP
      targetPort: db-port


---

# =========================
# == Load balancer for be-sample, allow it to be accessible publicly
# =========================
apiVersion: v1
kind: Service
metadata:
  name: be-sample
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: besample
spec:
  type: LoadBalancer
  selector:
    app: be-sample
  ports:
    - port: 8888
      name: http
      protocol: TCP
      targetPort: http

---

# =====================
# == Load balancer for fe-sample, allow it to be accessible publicly
# =====================
apiVersion: v1
kind: Service
metadata:
  name: fe-sample
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: fesample
spec:
  type: LoadBalancer
  selector:
    app: fe-sample
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http

