FROM nginx

COPY dist/webapp /usr/share/nginx/html
COPY docker/conf /etc/nginx

RUN apt -y update && \
    apt -y install apt-utils && \
    apt -y install curl

VOLUME /usr/share/nginx/html
VOLUME /etc/nginx
VOLUME /var/log/nginx

CMD ["nginx", "-g", "daemon off;"]

