FROM node:12

ENV NODE_ENV=development

WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./tsconfig.json ./

COPY ./src/ ./src/
COPY ./wait-for-db.sh ./

RUN apt -y update && \
    apt -y install mariadb-client-10.1 && \
    chmod u+x ./wait-for-db.sh && \
    npm install && \
    npm run compile

# CMD ["node", "src/app.js"]
